models:
  Subject:
    fields: {name: str, state: str}
  Recording:
    fields: {brain_region: str, probe_type: str, subject: FK→Subject}

meta:
  aliases:
    hippocampus: Hippocampus
    hippo: Hippocampus
    sleeping: REM
    neuropixels: Neuropixels
    awake: awake
